STUDENT_ID = '90849'

STUDENT_DIRECTORY = '/tmp/{0}'.format(STUDENT_ID)

LINDA_DIRECTORY = '{0}/linda'.format(STUDENT_DIRECTORY)

NETS_FILE_PATH = '{0}/nets'.format(LINDA_DIRECTORY)

TUPLE_FILE_PATH = '{0}/tuples'.format(LINDA_DIRECTORY)
